"""Initial migration

Revision ID: b590605b29b4
Revises: 10928c6477f3
Create Date: 2025-02-09 00:40:03.297278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b590605b29b4'
down_revision = '10928c6477f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BusinessRequests', schema=None) as batch_op:
        batch_op.alter_column('business_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('Bank', 'Financial Institution', 'Education', 'Other'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BusinessRequests', schema=None) as batch_op:
        batch_op.alter_column('business_type',
               existing_type=sa.Enum('Bank', 'Financial Institution', 'Education', 'Other'),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
